---
- hosts: all
  tasks:
    # - apt: package=emacs state=present
    - git: repo="https://github.com/lpenz/dotemacs.git" dest="{{lookup('env','HOME')}}/.emacs.d"
    - shell: emacs -nw --eval '(kill-emacs)' < /dev/tty
