---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker://lpenz/omnilint:0.5.2
  lint:
    strategy:
      matrix:
        emacs_version:
          - 29.4
          - 30.1
          - snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: purcell/setup-emacs@v7.0
        with:
          version: ${{ matrix.emacs_version }}
      - name: Check startup
        run: ./test-startup.sh
