---
name: CI
on: [ push, pull_request ]
jobs:
  omnilint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: docker://lpenz/omnilint:0.5.1
  lint:
    strategy:
      matrix:
        emacs_version:
          - 28.2
          - 29.1
          - snapshot
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.0.0
      - uses: purcell/setup-emacs@v6.0
        with:
          version: ${{ matrix.emacs_version }}
      - name: Check startup
        run: ./test-startup.sh
